language: scala

scala:
  - 2.10.2
  - 2.10.3

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - TERM=dumb

install:
  - gradle setupCIWorkspace

script: gradle buildNeeded

after_success:
  - gradle :Core:cobertura :Core:coveralls
