language: scala

scala:
  - 2.10.3

jdk:
  - openjdk7
  - openjdk6

env:
  - TERM=dumb PROJECT=Core
  - TERM=dumb PROJECT=Compatibility:BinniesMods:ExtraTrees:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:BiomesOPlenty:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:ExtraBiomesXL:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:Forestry:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:Natura:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:Thaumcraft:Materials:Wood
  - TERM=dumb PROJECT=Compatibility:Vanilla:Materials:Wood
  - TERM=dumb PROJECT=SeaCraft

install:
  - gradle :$PROJECT:setupCIWorkspace

script: gradle :$PROJECT:assemble

after_success:
  - gradle :$PROJECT:cobertura :$PROJECT:coveralls
