language: scala

scala:
  - 2.10.3

jdk:
  - openjdk7
  - openjdk6

env:
  - TERM=dumb PROJECT=Forge:Core
  - TERM=dumb PROJECT=Forge:Compatibility:BinniesMods:ExtraTrees:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:BiomesOPlenty:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:ExtraBiomesXL:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:Forestry:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:Natura:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:Thaumcraft:Materials:Wood
  - TERM=dumb PROJECT=Forge:Compatibility:Vanilla:Materials:Wood

install:
  - gradle :$PROJECT:setupCIWorkspace

script: gradle :$PROJECT:assemble

after_success:
  - gradle :$PROJECT:cobertura :$PROJECT:coveralls
