language: scala

scala: 2.10.3

jdk: openjdk7

env: TERM=dumb

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1efa01c1be5952beb05a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
